set MATLAB=C:\Program Files\MATLAB\R2017b
"C:\PROGRA~1\MATLAB\R2017b\bin\win64\gmake" -f ARDroneHover.mk  ISPROTECTINGMODEL=NOTPROTECTING EXTMODE_STATIC_ALLOC=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 TMW_EXTMODE_TESTING=0 OPTS="-DTGTCONN -DON_TARGET_WAIT_FOR_START=1"
